export function getBrightTheme() {
    var themeInfo = { 
        style: "Standard", 
        backgroundImg: "./Example/Images/Bright-Background.jpg", 
        backgroundOpacity: 0.3,
        colours: { 
            background: '#eef0f5',
            header: '#32475d14',
            headerBorder: '',
            headerShadow: '',
            logoPrimary: "#ffffff",
            logoSecondary: "#2d82db",
            headerButtons: '#4285f4',
            headerButtonsIcon: '#ffffff',
            headerButtonsText: '#ffffff',
            headerButtonsBorder: '',
            headerButtonsShadow: '',
            headerButtonsHover: '#3367d6',
            headerButtonsIconHover: '#ffffff',
            headerButtonsTextHover: '#ffffff',
            headerButtonsBorderHover: '',
            headerButtonsShadowHover: '',
            headerInputs: '#ffffff',
            headerInputsIcon: '#070b12',
            headerInputsText: '#070b12',
            headerInputsBorder: '',
            headerInputsShadow: '',
            headerInputsHover: '#eef0f5',
            headerInputsIconHover: '#070b12',
            headerInputsTextHover: '#070b12',
            headerInputsBorderHover: '',
            headerInputsShadowHover: '',
            headerProfile: '#ffffff',
            headerProfileTopLine: '#ffffff',
            headerProfileBottomLine: '#4285f4',
            headerProfileIcon: '#bac1d3',
            headerProfileBorder: '',
            headerProfileShadow: '',
            headerProfileHover: '#eef0f5',
            headerProfileTopLineHover: '#eef0f5',
            headerProfileBottomLineHover: '#3367d6',
            headerProfileIconHover: '#9da6bb',
            headerProfileBorderHover: '',
            headerProfileShadowHover: '',
            sideNav: '#32475d14',
            sideNavBorder: '#171e2a',
            sideNavShadow: '1px 0px 5px rgb(7 10 17 / 73%)'
        }
    }
    return themeInfo;
}
