export function getBrightTheme() {
    var themeInfo = { 
        style: "Standard", 
        backgroundImg: "./Example/Images/Bright-Background.jpg", 
        backgroundOpacity: 0.2,
        colours: { 
            background: '#eef0f5',
            header: '#32475d14',
            headerBorder: '',
            headerShadow: '',
            logoPrimary: "#ffffff",
            logoSecondary: "#2d82db",
            headerButtons: '#4285f4',
            headerButtonsIcon: '#ffffff',
            headerButtonsText: '#ffffff',
            headerButtonsBorder: '',
            headerButtonsShadow: '',
            headerButtonsHover: '#3367d6',
            headerButtonsIconHover: '#ffffff',
            headerButtonsTextHover: '#ffffff',
            headerButtonsBorderHover: '',
            headerButtonsShadowHover: '',
            headerInputs: '#ffffff',
            headerInputsIcon: '#070b12',
            headerInputsText: '#070b12',
            headerInputsBorder: '',
            headerInputsShadow: '',
            headerInputsHover: '#eef0f5',
            headerInputsIconHover: '#070b12',
            headerInputsTextHover: '#070b12',
            headerInputsBorderHover: '',
            headerInputsShadowHover: '',
            headerProfile: '#ffffff',
            headerProfileTopLine: '#ffffff',
            headerProfileBottomLine: '#4285f4',
            headerProfileIcon: '#bac1d3',
            headerProfileBorder: '',
            headerProfileShadow: '',
            headerProfileHover: '#eef0f5',
            headerProfileTopLineHover: '#eef0f5',
            headerProfileBottomLineHover: '#3367d6',
            headerProfileIconHover: '#9da6bb',
            headerProfileBorderHover: '',
            headerProfileShadowHover: '',
            sideNav: '#f8f8f8',
            sideNavBorder: '',
            sideNavShadow: '1px 0px 5px #979797ba',
            sideNavScrollBar: "#adadad",
            sideNavButtonsHover: "#eaeff4",
            sideNavButtonsBorderHover: "#d7d7d7",
            sideNavButtonsPrimaryIcons: "#4285f4",
            sideNavButtonsSecondaryIcons: "#EFEBF1",
            sideNavButtonsIconsBorder: "",
            sideNavButtonsText: "#26282c",
            sideNavButtonsTextHover: "red",
            subSideNav: '#f8f8f8',
            subSideNavBorder: '',
            subSideNavShadow: '1px 0px 5px #979797ba',
            subSideNavContrast: "#eaeff4",
            subSideNavContrastShadow: "inset 0px 0px 5px #81818140",
            subSideNavScrollBar: "#cecfd3",
            subSideNavText: "#26282c",
            subSideNavButtons: "#f8f8f8",
            subSideNavButtonsBorder: "#d7d7d7",
            subSideNavButtonsShadow: "1px 0px 5px #97979763",
            subSideNavButtonsHover: "#eaeff4",
            subSideNavButtonsText: "#26282c",
        },
        fonts: {
            fontSize: "14px",
            primaryFont: "sans-serif",
            primaryFontWeight: "normal",
            primaryFontSeparation: "normal",
            secondaryFont: "sans-serif",
            secondaryFontWeight: "normal",
            secondaryFontSeparation: "normal",
            headerPrimaryFont: "sans-serif",
            headerPrimaryFontWeight: "normal",
            headerPrimaryFontSeparation: "normal",
            headerSecondaryFont: "sans-serif",
            headerSecondaryFontWeight: "normal",
            headerSecondaryFontSeparation: "normal",
            sideNavFont: "sans-serif",
            sideNavFontWeight: "normal",
            sideNavFontSeparation: "normal"  
        }
    }
    return themeInfo;
}
