export function getFexillonTheme() {
    var themeInfo = { 
        style: "Standard", 
        backgroundImg: "./Example/Images/Fexillon-Background.svg", 
        backgroundOpacity: 1,
        fonts: {
            fontSize: "14px",
            primaryFont: "sans-serif",
            primaryFontWeight: "normal",
            primaryFontSeparation: "normal",
            secondaryFont: "sans-serif",
            secondaryFontWeight: "normal",
            secondaryFontSeparation: "normal",
            headerPrimaryFont: "sans-serif",
            headerPrimaryFontWeight: "normal",
            headerPrimaryFontSeparation: "1px",
            headerSecondaryFont: "sans-serif",
            headerSecondaryFontWeight: "bold",
            headerSecondaryFontSeparation: "normal"  
        },
        colours: { 
            background: '#ebebeb',
            header: '#747cfb',
            headerBorder: '',
            headerShadow: '1px 0px 5px rgb(66 68 119)',
            logoPrimary: "#ffffff",
            logoSecondary: "#2d82db",
            headerButtons: 'transparent',
            headerButtonsIcon: '#ffffff',
            headerButtonsText: '#ffffff',
            headerButtonsBorder: '',
            headerButtonsShadow: '',
            headerButtonsHover: 'transparent',
            headerButtonsIconHover: '#ecedff',
            headerButtonsTextHover: '#ecedff',
            headerButtonsBorderHover: '',
            headerButtonsShadowHover: '',
            headerInputs: '#ffffff',
            headerInputsIcon: '#253642',
            headerInputsText: '#253642',
            headerInputsBorder: '#50539d',
            headerInputsShadow: '',
            headerInputsHover: '#f5f6ff',
            headerInputsIconHover: '#253642',
            headerInputsTextHover: '#253642',
            headerInputsBorderHover: '#50539d',
            headerInputsShadowHover: '',
            headerProfile: '#ffffff',
            headerProfileTopLine: '#ffffff',
            headerProfileBottomLine: '#253642',
            headerProfileIcon: '#50539d',
            headerProfileBorder: '#50539d',
            headerProfileShadow: '',
            headerProfileHover: '#ecedff',
            headerProfileTopLineHover: '#ecedff',
            headerProfileBottomLineHover: '#253642',
            headerProfileIconHover: '#2d82db',
            headerProfileBorderHover: '#50539d',
            headerProfileShadowHover: '',
            sideNav: '#ffffff3d',
            sideNavBorder: '#d9d9e2',
            sideNavShadow: '0 1px 2px #0000001f'
        }
    }
    return themeInfo;
}