export function getFexillonTheme() {
    var themeInfo = { 
        style: "Standard", 
        backgroundImg: "./Example/Images/Fexillon-Background.svg",  
        backgroundOpacity: 1,
        colours: { 
            background: '#ebebeb',
            header: '#747cfb',
            headerBorder: '',
            headerShadow: '1px 0px 5px rgb(66 68 119)',
            logoPrimary: "#ffffff",
            logoSecondary: "#2d82db",
            headerButtons: 'transparent',
            headerButtonsIcon: '#ffffff',
            headerButtonsText: '#ffffff',
            headerButtonsBorder: '',
            headerButtonsShadow: '',
            headerButtonsHover: 'transparent',
            headerButtonsIconHover: '#ecedff',
            headerButtonsTextHover: '#ecedff',
            headerButtonsBorderHover: '',
            headerButtonsShadowHover: '',
            headerInputs: '#ffffff',
            headerInputsIcon: '#253642',
            headerInputsText: '#253642',
            headerInputsBorder: '#50539d',
            headerInputsShadow: '',
            headerInputsHover: '#f5f6ff',
            headerInputsIconHover: '#253642',
            headerInputsTextHover: '#253642',
            headerInputsBorderHover: '#50539d',
            headerInputsShadowHover: '',
            headerProfile: '#ffffff',
            headerProfileTopLine: '#ffffff',
            headerProfileBottomLine: '#253642',
            headerProfileIcon: '#50539d',
            headerProfileBorder: '#50539d',
            headerProfileShadow: '',
            headerProfileHover: '#ecedff',
            headerProfileTopLineHover: '#ecedff',
            headerProfileBottomLineHover: '#253642',
            headerProfileIconHover: '#2d82db',
            headerProfileBorderHover: '#50539d',
            headerProfileShadowHover: '',
            sideNav: '#f8f8f8',
            sideNavBorder: '',
            sideNavShadow: '1px 0px 5px #979797ba',
            sideNavScrollBar: "#adadad",
            sideNavButtonsHover: "#eaeff4",
            sideNavButtonsBorderHover: "#d7d7d7",
            sideNavButtonsPrimaryIcons: "#4285f4",
            sideNavButtonsSecondaryIcons: "#EFEBF1",
            sideNavButtonsIconsBorder: "",
            sideNavButtonsText: "#26282c",
            sideNavButtonsTextHover: "red",
            subSideNav: '#f8f8f8',
            subSideNavBorder: '',
            subSideNavShadow: '1px 0px 5px #979797ba',
            subSideNavContrast: "#eaeff4",
            subSideNavContrastShadow: "inset 0px 0px 5px #81818140",
            subSideNavScrollBar: "#cecfd3",
            subSideNavText: "#26282c",
            subSideNavButtons: "#f8f8f8",
            subSideNavButtonsBorder: "#d7d7d7",
            subSideNavButtonsShadow: "1px 0px 5px #97979763",
            subSideNavButtonsHover: "#eaeff4",
            subSideNavButtonsText: "#26282c",
        },
        fonts: {
            fontSize: "14px",
            primaryFont: "sans-serif",
            primaryFontWeight: "normal",
            primaryFontSeparation: "normal",
            secondaryFont: "sans-serif",
            secondaryFontWeight: "normal",
            secondaryFontSeparation: "normal",
            headerPrimaryFont: "sans-serif",
            headerPrimaryFontWeight: "normal",
            headerPrimaryFontSeparation: "1px",
            headerSecondaryFont: "sans-serif",
            headerSecondaryFontWeight: "bold",
            headerSecondaryFontSeparation: "normal",
            sideNavFont: "sans-serif",
            sideNavFontWeight: "normal",
            sideNavFontSeparation: "normal"  
        }
    }
    return themeInfo;
}
