export function getTeamsTheme() {
    var themeInfo = { 
        style: "Standard", 
        colours: { 
            background: '#f5f5f5',
            header: '#444791',
            headerBorder: '',
            headerShadow: '',
            logoPrimary: "#ffffff",
            logoSecondary: "#2f2f4a",
            headerButtons: 'transparent',
            headerButtonsIcon: '#ffffff',
            headerButtonsText: '#ffffff',
            headerButtonsBorder: '',
            headerButtonsShadow: '',
            headerButtonsHover: 'transparent',
            headerButtonsIconHover: '#eef0f5',
            headerButtonsTextHover: '#eef0f5',
            headerButtonsBorderHover: '',
            headerButtonsShadowHover: '',
            headerInputs: '#ffffff',
            headerInputsIcon: '#2f2f4a',
            headerInputsText: '#2f2f4a',
            headerInputsBorder: '',
            headerInputsShadow: '',
            headerInputsHover: '#eef0f5',
            headerInputsIconHover: '#2f2f4a',
            headerInputsTextHover: '#2f2f4a',
            headerInputsBorderHover: '',
            headerInputsShadowHover: '',
            headerProfile: '#ffffff',
            headerProfileTopLine: '#ffffff',
            headerProfileBottomLine: '#2f2f4a',
            headerProfileIcon: '#bac1d3',
            headerProfileBorder: '',
            headerProfileShadow: '',
            headerProfileHover: '#eef0f5',
            headerProfileTopLineHover: '#eef0f5',
            headerProfileBottomLineHover: '#2f2f4a',
            headerProfileIconHover: '#9da6bb',
            headerProfileBorderHover: '',
            headerProfileShadowHover: '',
            sideNav: '#f5f5f5',
            sideNavBorder: '#d9d9e2',
            sideNavShadow: 'inset 0 1px 10px #00000033'
        }
    }
    return themeInfo;
}
