export function getDefaultFonts() {
    var fonts = {
        fontSize: "13px",
        primaryFont: "sans-serif",
        primaryFontWeight: "normal",
        primaryFontSeparation: "normal",
        secondaryFont: "sans-serif",
        secondaryFontWeight: "normal",
        secondaryFontSeparation: "normal",
        headerPrimaryFont: "sans-serif",
        headerPrimaryFontWeight: "normal",
        headerPrimaryFontSeparation: "normal",
        headerSecondaryFont: "sans-serif",
        headerSecondaryFontWeight: "normal",
        headerSecondaryFontSeparation: "normal",
        sideNavFont: "sans-serif",
        sideNavFontWeight: "normal",
        sideNavFontSeparation: "normal"  
    }
    return fonts;
}

export function getDefaultColours() {
    var colours = { 
        background: '#141526',
        header: '#32475d14',
        headerBorder: '#171e2a',
        headerShadow: '1px 0px 5px rgb(7 10 17 / 73%)',
        logoPrimary: "#ffffff",
        logoSecondary: "#2d82db",
        headerButtons: '#4285f4',
        headerButtonsIcon: '#ffffff',
        headerButtonsText: '#ffffff',
        headerButtonsBorder: '#171e2a',
        headerButtonsShadow: '0 2px 5px rgba(66, 133, 244, 0.3)',
        headerButtonsHover: '#3367d6',
        headerButtonsIconHover: '#ffffff',
        headerButtonsTextHover: '#ffffff',
        headerButtonsBorderHover: '#1a3e8c',
        headerButtonsShadowHover: '0 2px 5px rgba(33, 67, 125, 0.3)',
        headerInputs: '#080a1050',
        headerInputsIcon: '#2d82db',
        headerInputsText: '#e3e6ef',
        headerInputsBorder: '#171e2a',
        headerInputsShadow: 'inset 1px 1px 5px rgb(7 10 17 / 60%)',
        headerInputsHover: '#080a1075',
        headerInputsIconHover: '#2d82db',
        headerInputsTextHover: '#e3e6ef',
        headerInputsBorderHover: '#171e2a',
        headerInputsShadowHover: 'inset 1px 1px 5px rgb(7 10 17 / 60%)',
        headerProfile: '#080a108f',
        headerProfileTopLine: '#e3e6ef',
        headerProfileBottomLine: '#2d82db',
        headerProfileIcon: '#2d82db',
        headerProfileBorder: '#171e2a',
        headerProfileShadow: '1px 0px 5px rgb(7 10 17 / 73%)',
        headerProfileHover: '#080a10cf',
        headerProfileTopLineHover: '#e3e6ef',
        headerProfileBottomLineHover: '#2d82db',
        headerProfileIconHover: '#2d82db',
        headerProfileBorderHover: '#353d4b',
        headerProfileShadowHover: '1px 0px 5px rgb(7 10 17 / 73%)',
        sideNav: '#32475d14',
        sideNavBorder: '#171e2a',
        sideNavShadow: '1px 0px 5px rgb(7 10 17 / 73%)',
        sideNavScrollBar: "#233952",
        sideNavButtonsHover: "#507eaf17",
        sideNavButtonsBorderHover: "#171e2a",
        sideNavButtonsPrimaryIcons: "#4285f4",
        sideNavButtonsSecondaryIcons: "#EFEBF1",
        sideNavButtonsIconsBorder: "",
        sideNavButtonsText: "#e3e6ef",
        sideNavButtonsTextHover: "red",
        subSideNav: '#32475d14',
        subSideNavBorder: '#171e2a',
        subSideNavShadow: '1px 0px 5px rgb(7 10 17 / 73%)',
        subSideNavContrast: "#14151b78",
        subSideNavContrastShadow: "inset 0px 0px 5px #0000005c",
        subSideNavScrollBar: "#233952",
        subSideNavText: "#e3e6ef",
        subSideNavButtons: "#507eaf17",
        subSideNavButtonsBorder: "#171e2a",
        subSideNavButtonsShadow: "1px 0px 5px #070a11ba",
        subSideNavButtonsHover: "#6ca3de33",
        subSideNavButtonsText: "#e3e6ef",
    }
    return colours;
}
